---
abstract: 'Cross-platform basic tests for scripts'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::Builder: 0.32
  Test::Builder::Tester: 1.02
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Script
name: Test-Script
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0.80
  IPC::Run3: 0.034
  Probe::Perl: 0.01
  blib: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.04_03
