abstract: Cross-platform basic tests for scripts
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::Builder: 0.32
  Test::Builder::Tester: 1.02
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Test-Script
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Exporter: 0
  File::Spec: 0.80
  IPC::Run3: 0.034
  perl: 5.005
version: 1.02
